### ISSUE TITLE
Charging Current setting

### ISSUE THREAD

**Issue by deqw** [dannerph/homeassistant-keba#21]
The Charging Current setting 'defaults' to 12 while SolarEdge EV Charger settings show 16A. Are these values about the same setting?

![Screenshot 2023-10-23 at 17 05 40](https://github.com/dannerph/homeassistant-keba/assets/65849349/25bf54da-471a-4c05-aee0-ddb7fc7bb534)

![Screenshot 2023-10-25 at 14 55 47](https://github.com/dannerph/homeassistant-keba/assets/65849349/53a1f86d-2ded-4c9a-b029-7ba4c81f9ae1)

(That slider is at: 12)

**Comment by spali** [comment]
Correct me if I'm wrong, but the slider is more like only an input which will send the request to the Keba on change.
But there are multiple other sensors from this integration, that will show current (A) values (some are by default hidden).
Keba has multiple current limits that plays into the actual max current.
From my overvations (may be wrong):

**Set current** -> the current selected in your slider when actually accepted by the Keba for the current or next charging session.
**Maximum current (system)** -> the "final result" that will be the limiting factor. At least it changes depending on the selected value and other system setting related values.

There are also some other sensor with the other system or setting related limits.
Not sure what solare edge is showing, maybe just the system and settings related limits, not what you actual set for the charging session.

**Comment by deqw** [comment]
@spali OK thanks, that pointed me to the hidden sensors so I enabled a few more.

![Screenshot 2023-10-25 at 14 43 53](https://github.com/dannerph/homeassistant-keba/assets/65849349/41688259-07ec-4a89-bd9a-7ada553c89f3)

So it looks like 'Current hardware' is the SolarEdge 'Max charging current'. Still not clear to me what the slider exactly does because it always reverts to 12A. But maybe that is a SolarEdge thing.

**Comment by spali** [comment]
Try to remove the solare edge inverter from the network and check if it still reverts.... but yes I also assume solare edge is setting it back to 12A ... maybe some kind of default value from it. 
I also have a solare edge inverter but the non branded keba and even it may be possible, I didn't integrate the keba into the inverter, because I set the current by automations. It may also be possible to drop it from the inverter and use the keba feature for excess usage. But not tried it yet, as the inverter only accepts 1 modbus connection and this connection is used by the HA integration. I would need to setup something like a modbus multiplexer.

**Comment by deqw** [comment]
@spali I can flash the Keba P30x firmware to replace the SolarEdge firmware, I think, but am not sure about the side effects or risk to brick it. I'm doing the automation with HA/Node-Red and running the inverter in 'Remote Control' only, which works very good for home battery charging and optimal pricing usage. I'm in the mySolarEdge beta but the rolled out new options aren't very promising and/or not suitable for my situation, so not making use of it. As for the EV charger I'm running into an Authorization Rejected situation (see Issue #20)  when trying to start charging via this integration, probably a SolarEdge quirk too (eg. missing key or something like that). Did you have to deal with that too?

**Comment by spali** [comment]
No, but as written, I control the Keba completely by myself with home assistant. I automated a family members Keba with the electrical X1 external input to start or stop charging. And my own I do by sending the RFID authorization via the integration in home assistant (didn't had much success with only start/stop charging via integration).
Because I also have problems, that my both cars don't like to much start/stop after a while, I may need a switch for the CP wire to completely reset both sides (like unplug the cable). So I may need anyway a relay in the Keba and may then switch to the X1 solution too.
Regarding #20, no idea how it works with Solar Edge, sounds like they control the Keba... maybe the use OCPP protocol to control from the SE servers. So I assume you should contact the Solar Edge support. I don't think this integration messes with the Keba on it's own without you executing anything.

**Comment by deqw** [comment]
"maybe the use OCPP protocol to control from the SE servers", I think you are right. I have to trigger charging with the SolarEdge app before I can get charging going again. I'm not using RFID authorization BTW. Well, thanks for the conversation!
